### ISSUE TITLE
Undefined payload

### ISSUE THREAD

**Issue by P4sca1** [mscdex/ssh2-streams#106]
I am using the ssh2 package to create my own sftp server.
It got to a state where quite all sftp functions are supported and working - at least on Filezilla.
I just tried Cyberduck and I do get this error sometimes, especially when uploading large folders:

```
/Users/pascal/code/ips-hosting-daemon/node_modules/ssh2-streams/lib/ssh.js:5292
  pktLen = payload.length + 9;
                   ^

TypeError: Cannot read property 'length' of null
    at send_ (/Users/pascal/code/ips-hosting-daemon/node_modules/ssh2-streams/lib/ssh.js:5292:20)
    at /Users/pascal/code/ips-hosting-daemon/node_modules/ssh2-streams/lib/ssh.js:5272:7
    at afterWrite (_stream_writable.js:455:3)
    at onwrite (_stream_writable.js:446:7)
    at Deflate.afterTransform (_stream_transform.js:89:3)
    at Zlib.processCallback (zlib.js:572:8)
```

Any idea what could be the reason and how I can prevent it?

**Comment by mscdex** [comment]
Others have encountered issues with Cyberduck and compression before, so in that case you should explicitly disable compression support with `algorithms: { compress: ['none'] }` in your ssh2 server configuration.

**Comment by P4sca1** [comment]
Okay, thank you for the hint!
