### ISSUE TITLE
Error: PEM_read_bio_PUBKEY failed when using node 8

### ISSUE THREAD

**Issue by mitchheddles** [mscdex/ssh2-streams#113]
I'm noticing an error which seems to be coming from node `crypto`, more specifically `Verify.verify ` when using node 8 and above (possibly 7), but not 6.

```
DEBUG: Host accepted by default (no verification)
DEBUG: format: ssh-rsa
DEBUG: format: RSA-SHA1
DEBUG: Verifying signature
crypto.js:379
  return this._handle.verify(toBuf(key), toBuf(signature, sigEncoding),
                      ^

Error: PEM_read_bio_PUBKEY failed
    at Verify.verify (crypto.js:379:23)
    at onKEXDH_REPLY (/Users/mitch/Development/wp-scripts/node_modules/ssh2-streams/lib/ssh.js:2904:27)
    at SSH2Stream.<anonymous> (/Users/mitch/Development/wp-scripts/node_modules/ssh2-streams/lib/ssh.js:215:45)
    at emitOne (events.js:115:13)
    at SSH2Stream.emit (events.js:210:7)
    at parse_KEXDH_REPLY (/Users/mitch/Development/wp-scripts/node_modules/ssh2-streams/lib/ssh.js:4222:8)
    at parse_KEX (/Users/mitch/Development/wp-scripts/node_modules/ssh2-streams/lib/ssh.js:4168:16)
    at parsePacket (/Users/mitch/Development/wp-scripts/node_modules/ssh2-streams/lib/ssh.js:4019:12)
    at SSH2Stream._transform (/Users/mitch/Development/wp-scripts/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
error Command failed with exit code 1.
```

Looking in the error led me to [lib/ssh.js](https://github.com/mscdex/ssh2-streams/blob/master/lib/ssh.js#L2905).

It seems to work by converting the key and signature to buffers, but I'm not 100% sure why.

```var verified = verifier.verify(Buffer.from(fullkey), Buffer.from(rawsig));```

Happy to make a PR if this looks alright.

**Comment by mscdex** [comment]
Do you have a way to reproduce the error? Currently `ssh2` (and thus `ssh2-streams`) is passing all tests with node v8.x and node v10.x.

**Comment by mitchheddles** [comment]
I'll try set one up, just FYI I'm using [tunnel-ssh](https://github.com/agebrock/tunnel-ssh) at the moment which has `ssh2` as a dependency.

**Comment by mscdex** [comment]
It looks like `tunnel-ssh` has `ssh2` and `ssh2-streams` pegged at some older versions (especially due to their package-lock.json), perhaps that is causing problems?

**Comment by mitchheddles** [comment]
I've setup a small repo which you can use to reproduce the error.
https://github.com/mitchheddles/ssh-streams-issue

You will just need to specify a working host, user and password so you can make a connection.

It may not be ssh-streams issue, but maybe [colors.js](https://github.com/Marak/colors.js) and it not liking theme colors with the name `key`, in saying that, the `Buffer.from` fix from above does solve the problem.

**Comment by mscdex** [comment]
It looks like `colors` does mutate `String.prototype` and other things which is not a good idea, so that could be somehow causing the string check to fail in node core.

On a related note, I see you're trying to tunnel MySQL connections over SSH. If you're only making the database connections from within your node process, you can avoid listening on a local port by using a combination of `mysql2` (which supports using an arbitrary stream for the underlying connection and is most likely still faster too) and `ssh2` directly.

**Comment by mitchheddles** [comment]
Thanks @mscdex I'll look into it, but for now I've just changed my colors theme to not use `key`.
