### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by sean256** [mscdex/ssh2-streams#119]
Tested OS's: Mac OS 10.14 and Ubuntu

When I use `scp` or the the app Cyberduck to upload a 10MB file it uploads at ~5.4MB/s and finishes it less than 2 seconds. This is from my machine or an ec2 instance in AWS.

Using this library with `createWriteStream` it takes 30 seconds. I tried `fastPut` and that errors out with `General Error`. After some trial and error I found that `fastPut` against this particular server only works with `{ concurrency: 1 }`.

**Comment by mscdex** [comment]
If the server only allows one outstanding write request at any given time, then there's not really anything that can be done as OpenSSH (and probably other) clients depend on concurrent reads/writes to improve throughput.

**Comment by sean256** [comment]
That’s the thing, I’m not so sure it’s due to the lack of concurrent writes. If the server didn’t allow it why is Cyberduck or scp able to blast through the file?

**Comment by mscdex** [comment]
If it's true `scp` then it's not using sftp at all. You could probably get something equivalent by simply doing something like:

```js
ssh.exec('cat > /path/to/write/to', (err, stream) => {
  if (err) throw err;
  fs.createReadStream('/path/to/read/from').pipe(stream).on('finish', () => ssh.end());
});
```

**Comment by sean256** [comment]
Thanks for suggestion. Looks like the server doesn't support exec either. 🤷‍♂️
