### ISSUE TITLE
SFTP slow - increase chunk size?

### ISSUE THREAD

**Issue by jeffrson** [mscdex/ssh2-streams#120]
Hi,

I built an SFTP server (based on ssh2/ssh2-streams) and I'm running a couple of instances inside a LAN.

Then I have a client (based as well on ssh2/ssh2-streams) which copies data from one server to another.

I'm using createReadStream and createWriteStream and pipe them together. Unfortunately this seems rather slow: 60MB in 1.5min :-(

My guess is, it's the chunk size of 32kb that slows it down.

Is there an easy way to increase the chunk size? Would you expect it to be faster?

Any other idea?

Thanks!

**Comment by mscdex** [comment]
You will get better performance by implementing parallel reads/writes, similar to what `fastPut()`/`fastGet()` does.

**Comment by mscdex** [comment]
Alternatively if you want even more speed, piping a tarball from one server to another with `.exec()` will be even faster because SFTP does add overhead, even with parallel reads/writes.
