### ISSUE TITLE
Unexpected packet before version?

### ISSUE THREAD

**Issue by Chittipobng014** [mscdex/ssh2-streams#121]
I've got this error

Error: Unexpected packet before version
    at SFTPStream._transform (/Users/Army/Documents/Ministry Of Data Workspace/InternshipBackendProject/node_modules/ssh2-streams/lib/sftp.js:308:27)
    at SFTPStream.Transform._read (_stream_transform.js:190:10)
    at SFTPStream._read (/Users/Army/Documents/Ministry Of Data Workspace/InternshipBackendProject/node_modules/ssh2-streams/lib/sftp.js:184:15)
    at SFTPStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at SFTPStream.Writable.write (_stream_writable.js:299:11)
    at Channel.ondata (_stream_readable.js:693:20)
    at Channel.emit (events.js:197:13)
    at Channel.EventEmitter.emit (domain.js:439:20)

**Comment by mscdex** [comment]
Can you post debug output (`debug: console.log` in the connection config object), censoring ip/port if necessary?

**Comment by Chittipobng014** [comment]
> Can you post debug output (`debug: console.log` in the connection config object), censoring ip/port if necessary?

SSH {
  connection:
   Client {
     domain: null,
     _events:
      [Object: null prototype] { ready: [Function], end: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     config:
      { host: 'Host',
        port: 22,
        forceIPv4: false,
        forceIPv6: false,
        keepaliveCountMax: 3,
        keepaliveInterval: 0,
        readyTimeout: 20000,
        username: 'root',
        password: undefined,
        privateKey: [Object],
        publicKey: [Object],
        tryKeyboard: false,
        agent: undefined,
        allowAgentFwd: false,
        hostHashAlgo: undefined,
        hostHashCb: undefined,
        strictVendor: true,
        debug: [Function: DEBUG_NOOP],
        localHostname: undefined,
        localUsername: undefined },
     _readyTimeout:
      Timeout {
        _idleTimeout: -1,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 6953,
        _onTimeout: null,
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: null,
        [Symbol(asyncId)]: 197,
        [Symbol(triggerId)]: 0 },
     _channels: {},
     _callbacks: [],
     _forwarding: {},
     _forwardingUnix: {},
     _acceptX11: 0,
     _agentFwdEnabled: false,
     _curChan: -1,
     _remoteVer: 'OpenSSH_7.6p1',
     _sshstream:
      SSH2Stream {
        _readableState: [ReadableState],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 19,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: true,
        _transformState: [Object],
        _needContinue: false,
        bytesReceived: 512,
        bytesSent: 1184,
        debug: [Function: DEBUG_NOOP],
        server: false,
        maxPacketSize: 35000,
        remoteBugs: 0,
        config: [Object],
        _state: [Object] },
     _sock:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: 'Host,
        _readableState: [ReadableState],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 9,
        _maxListeners: 0,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        timeout: 0,
        [Symbol(asyncId)]: 198,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     _resetKA: [Function: resetKA] } }

**Comment by Chittipobng014** [comment]
> Can you post debug output (`debug: console.log` in the connection config object), censoring ip/port if necessary?

SSH2Stream {
  _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 32768,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: 'host',
        _readableState: [ReadableState],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 9,
        _maxListeners: 0,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        timeout: 0,
        [Symbol(asyncId)]: 138,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     pipesCount: 1,
     flowing: true,
     ended: false,
     endEmitted: false,
     reading: false,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     paused: false,
     emitClose: true,
     autoDestroy: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  domain: null,
  _events:
   [Object: null prototype] {
     prefinish: [Function: prefinish],
     end: [ [Function], [Function] ],
     DISCONNECT: [Function],
     KEXINIT: [Function],
     NEWKEYS: [Function],
     KEXDH_REPLY: [Function],
     KEXDH_GEX_GROUP: [Function],
     USERAUTH_BANNER: [Function],
     drain: [ [Function], [Function: pipeOnDrainFunctionResult] ],
     continue: [Function],
     error: [ [Function: onerror], [Function] ],
     CHANNEL_OPEN: [Function],
     REQUEST_SUCCESS: [Function],
     REQUEST_FAILURE: [Function],
     GLOBAL_REQUEST: [Function],
     data: [Function: ondata],
     unpipe: [Function: onunpipe],
     close:
      { [Function: bound onceWrapper] listener: [Function: onclose] },
     finish:
      { [Function: bound onceWrapper] listener: [Function: onfinish] } },
  _eventsCount: 19,
  _maxListeners: undefined,
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 32768,
     finalCalled: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     destroyed: false,
     decodeStrings: true,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: false,
     bufferProcessing: false,
     onwrite: [Function: bound onwrite],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     emitClose: true,
     autoDestroy: false,
     bufferedRequestCount: 0,
     corkedRequestsFree:
      { next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] } },
  writable: true,
  allowHalfOpen: true,
  _transformState:
   { afterTransform: [Function: bound afterTransform],
     needTransform: true,
     transforming: false,
     writecb: null,
     writechunk: null,
     writeencoding: 'buffer' },
  _needContinue: false,
  bytesReceived: 512,
  bytesSent: 1184,
  debug: [Function: DEBUG_NOOP],
  server: false,
  maxPacketSize: 35000,
  remoteBugs: 0,
  config:
   { hostKeys: undefined,
     ident: 'SSH-2.0-ssh2js0.1.20',
     algorithms:
      { kex: [Array],
        kexBuf:
         <Buffer 65 63 64 68 2d 73 68 61 32 2d 6e 69 73 74 70 32 35 36 2c 65 63 64 68 2d 73 68 61 32 2d 6e 69 73 74 70 33 38 34 2c 65 63 64 68 2d 73 68 61 32 2d 6e 69 ... 71 more bytes>,
        serverHostKey: [Array],
        serverHostKeyBuf:
         <Buffer 73 73 68 2d 72 73 61 2c 65 63 64 73 61 2d 73 68 61 32 2d 6e 69 73 74 70 32 35 36 2c 65 63 64 73 61 2d 73 68 61 32 2d 6e 69 73 74 70 33 38 34 2c 65 63 ... 17 more bytes>,
        cipher: [Array],
        cipherBuf:
         <Buffer 61 65 73 31 32 38 2d 63 74 72 2c 61 65 73 31 39 32 2d 63 74 72 2c 61 65 73 32 35 36 2d 63 74 72 2c 61 65 73 31 32 38 2d 67 63 6d 2c 61 65 73 31 32 38 ... 50 more bytes>,
        hmac: [Array],
        hmacBuf:
         <Buffer 68 6d 61 63 2d 73 68 61 32 2d 32 35 36 2c 68 6d 61 63 2d 73 68 61 32 2d 35 31 32 2c 68 6d 61 63 2d 73 68 61 31>,
        compress: [Array],
        compressBuf:
         <Buffer 6e 6f 6e 65 2c 7a 6c 69 62 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 7a 6c 69 62> } },
  _state:
   { authsQueue: [],
     hostkeyFormat: 'ssh-rsa',
     kex: ECDH { [Symbol(kHandle)]: {} },
     kexdh: 'ec-sha256',
     incoming:
      { status: 4,
        expectedPacket: undefined,
        search: undefined,
        greeting: undefined,
        seqno: 7,
        pktLen: 12,
        padLen: 10,
        pktExtra: undefined,
        payload: undefined,
        packet: undefined,
        kexinit: undefined,
        identRaw: 'SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.2',
        rekeyQueue: [],
        ignoreNext: false,
        expect: [Object],
        decrypt: [Object],
        hmac: [Object],
        decompress: [Object] },
     outgoing:
      { status: 9,
        seqno: 7,
        bufSeqno: <Buffer 00 00 00 06>,
        rekeyQueue: [],
        kexinit: undefined,
        kexsecret: undefined,
        pubkey:
         <Buffer 04 9b c4 a2 96 e4 cf fa 70 96 e1 b0 a3 0e 23 6c 95 6d 4a d9 bb 18 88 82 e6 d5 e7 49 1d 5f 2c ff 63 65 44 fc 57 ba dd 42 0c a9 a4 8d a2 30 f0 0f d6 4b ... 15 more bytes>,
        exchangeHash: undefined,
        sessionId:
         <Buffer 57 82 92 86 c0 c8 60 b9 51 ec 32 b3 f4 2b 2b c7 06 ec e1 16 d3 70 44 17 9a 9f 75 11 31 0b 71 bf>,
        sentNEWKEYS: true,
        encrypt: [Object],
        hmac: [Object],
        compress: [Object] } } }

**Comment by mscdex** [comment]
I meant set `debug: console.log` in your connection config object that you pass to `.connect()` and post the resulting output to your console.

**Comment by Chittipobng014** [comment]
> I meant set `debug: console.log` in your connection config object that you pass to `.connect()` and post the resulting output to your console.

You mean this one?

{ host: 'host',
  privateKey: '/Users/Army/Documents/surveysystem.pem',
  username: 'root' }

**Comment by Chittipobng014** [comment]
> I meant set `debug: console.log` in your connection config object that you pass to `.connect()` and post the resulting output to your console.

Solved !!!
It's fault of configuring of user name in ftp-kr.json. Amazon EC2 server name uses 'Ubuntu' , not 'root'. I changed it and this error has disappeared

ref: https://github.com/karikera/ftp-kr/issues/96
