### ISSUE TITLE
Dynamic requires

### ISSUE THREAD

**Issue by medikoo** [mscdex/ssh2-streams#123]
Any specific reason for requires written as below:

https://github.com/mscdex/ssh2-streams/blob/1845aff4ad1ad086bee1f8612e031d9bea931bb8/lib/keyParser.js#L17

It'll work perfectly if written just as `require('./buffer-helpers')` while in dynamic form it raises issues for any static analysis that resolves require chain.

**Comment by mscdex** [comment]
Probably no specific reason

**Comment by medikoo** [comment]
Created PR that ensures static require paths: https://github.com/mscdex/ssh2-streams/pull/124

**Comment by keksipurkki** [comment]
I also bumped into this while trying to bundle my code with rollup.

**Comment by mscdex** [comment]
https://github.com/mscdex/ssh2-streams/pull/124 was merged.
