### ISSUE TITLE
Auto file mode for SFTPStream.createWriteStream?

### ISSUE THREAD

**Issue by zxdong262** [mscdex/ssh2-streams#128]
I use createReadStream/createWriteStream to download/upload, I find that when remove mode option, download process will be smart auto: when overwrite, keep local file's mode, if no overwrite, use remote file's mode, but for upload process, this do not work like that, if no mode setting in options, it will always be 0o666.

Just wondering that could `SFTPStream.createWriteStream` be that smart? or I missed something?

```js
  let option = {mode}
  let readSteam = type === 'download'
      ? sftp.createReadStream(remotePath, options)
      : fs.createReadStream(localPath, options)
    let writeSteam = type === 'download'
      ? fs.createWriteStream(localPath, options)
      : sftp.createWriteStream(remotePath, options)
```

**Comment by mscdex** [comment]
`sftp.createWriteStream()` intentionally works the same way as `fs.createWriteStream()`, which is if you don't specify a `mode` option it will default to `0o666`.

For the opposite (remote -> local), there is no way that node magically knows what the remote file mode was unless you explicitly provide it as they (`sftp.createReadStream()` and `fs.createWriteStream()`) are just streams of file data. The fact that it may be working as you expect *without* a `mode` set is just coincidence.

**Comment by zxdong262** [comment]
@mscdex Thank you!
