### ISSUE TITLE
Tag release for EdDSA support

### ISSUE THREAD

**Issue by moderndeveloperllc** [mscdex/ssh2-streams#131]
There are a few projects that I'm following that utilize ssh-streams for SSH tunneling. It would be great to get this functionality tagged for release if possible so they can pull it into their workflow. Trying to switch everything over to EdDSA during migrations.

**Comment by mscdex** [comment]
It's not that simple, there isn't a node release yet that supports the necessary APIs (along with OpenSSL 1.1.1+) to utilize EdDSA. I was just incorporating the code so it will be ready when that time comes. Right now those APIs will be available at least in the upcoming node v12.0.0. I'm not sure if they will be backported to older branches or not yet.

**Comment by moderndeveloperllc** [comment]
@mscdex GTK. Guess I'll get to hang onto RSA for the time being!
