### ISSUE TITLE
Since 0.4.3 sftp.fastPut() sends the first 32k block multiple times

### ISSUE THREAD

**Issue by eemeli** [mscdex/ssh2-streams#133]
It would appear that with the latest version larger SFTP uploads using `fastPut()` get corrupted, resulting in files with the correct byte count but with contents that repeat the first 32768 bytes.

Apologies for not being able to provide a working sample, this came up as an internal CD tool that uses `ssh2` and `ssh2-promise` started producing broken deployments.

**Comment by eemeli** [comment]
I added a workaround for this locally by fixing the `ssh2-streams` version to 0.4.2, with which `sftp.fastPut()` works without problems.

**Comment by mscdex** [comment]
Should be fixed by 5577db5ddb372887808c63c047ae3b9b6235a5a3.
