### ISSUE TITLE
issue on [v0.4.5] sftp task is breaking during build

### ISSUE THREAD

**Issue by G1jeeva10** [mscdex/ssh2-streams#146]
Following error appears in my deployment log from Monday. Traced the issue back to ssh2-streams/lib/sftp.js line number 2675.

following is the error log.
/node_modules/gulp-sftp/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:2675
var {
    ^
SyntaxError: Unexpected token {

Requesting help to resolve the above issue.
Thanks

**Comment by mscdex** [comment]
FWIW this indicates an unsupported version of node as object destructuring has been around for a long time. Nonetheless I've replaced its usage for now.
