### ISSUE TITLE
What is a handle?

### ISSUE THREAD

**Issue by Fransebas** [mscdex/ssh2-streams#147]
Hi, I've been using your library and it's really amazing thanks! 

And while using it I had a question, What exactly is the handle? I mean, what information is on the buffer? Only an id for the file or does it have the path and everything? I couldn't find the answer in the documentation, but maybe I didn't read it thoroughly.

**Comment by mscdex** [comment]
I'm assuming you're referring to SFTP here. It should be treated as an opaque blob used to refer to an open file/directory.

**Comment by Fransebas** [comment]
Yes, I'm referring to the SFTP, okay so I'm going to use it as an ID for the file.

Also, What is the recommended use for `open`, `read` and `write`, should I use `open` every time I'm going to do a `read` or a `write` or should I reuse the handle?

**Comment by mscdex** [comment]
You can reuse the handle until you close it.
