### ISSUE TITLE
Wrong requirement in README, node version should >= 5.10.0

### ISSUE THREAD

**Issue by XeroAlpha** [mscdex/ssh2-streams#148]
ssh2-streams cannot run when node version is 5.2.0, because Buffer.from is used. Buffer.from is included in node version 5.10.0. ssh2 cannot run when node version is 5.2.0 too. See [Buffer | Node.js Documentation](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_string_encoding).

**Comment by mscdex** [comment]
Fixed in 881cf9cd47cc52df03e6afca52520dd56440b3da.
