### ISSUE TITLE
How to return the default CIPHER ssh2 is using?

### ISSUE THREAD

**Issue by blhagadorn** [mscdex/ssh2-streams#150]
Hi all, I am looking at this list here: https://github.com/mscdex/ssh2-streams/blob/a979592f13ee06ad9d5245eef17b0535f7354cce/lib/constants.js#L259 and am curious to know which actual algorithm will be used for my client? My SFTP server is updating their list of allowed ciphers so I want to make sure I am ok or if I potentially need to update my default config on `connect()`.

Thanks for any help!

**Comment by mscdex** [comment]
There is no public API to obtain that information programmatically at the moment. You can see it in the debug output however if for example you set `debug: console.log` in your connection config object. In the debug output you will see all of the algorithms `ssh2` offers, what the server offers, and what the negotiated algorithm was, for both directions (client to server and vice versa).

**Comment by blhagadorn** [comment]
Thanks for the answer, this may be a silly question/thought, but it's my understanding that as long is there is a common overlap between the DEFAULT list of ciphers and the ciphers on the SFTP server side, then the connection will negotiate one of the ones that it has in common?  If there is no overlap at all then I should specify in my `client.connect()` configuration, right?

**Comment by mscdex** [comment]
Basically, yes. However, you're still limited to the algorithms that are supported, so you can't just add just any arbitrary algorithm name and have it just work.

**Comment by blhagadorn** [comment]
Thanks! Really appreciate you taking the time to answer this question.
