### ISSUE TITLE
Posix rename support

### ISSUE THREAD

**Issue by aleks-m** [mscdex/ssh2-streams#152]
Hi

Could you please add support for posix rename (posix-rename@openssh.com extension)?
It would allow renaming a file even if a destination already exists in one operation and without any additional steps.

Thanks.

**Comment by jhorbulyk** [comment]
Unfortunately, [even though this feature is defined in the latest SFTP RFC](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-04#section-6.5), it looks like this operation isn't supported in many SFTP implementations. As a result, many SFTP clients revert to an exist check, followed by a possible delete request, followed by a rename request.  [See Cyberduck for one such implementation.](https://github.com/iterate-ch/cyberduck/blob/09dfa563dc82e9833dfe71bacccc3e6f3e49ba4e/ssh/src/main/java/ch/cyberduck/core/sftp/SFTPMoveFeature.java#L44-L47)

**Comment by mscdex** [comment]
Support for the OpenSSH rename extension already exists via `sftp.ext_openssh_rename()`.
