### ISSUE TITLE
Batch stat call from client

### ISSUE THREAD

**Issue by Fransebas** [mscdex/ssh2-streams#154]
Hello, I was wondering if there is a way to batch multiple stat calls because I need to display if the files that I'm getting are folders or files to show the right icon and it's really slow because I have to fetch all the files inside a folder and then call a stat for each file. 

So sending a batch is an option or maybe there is another way that I'm not aware of.

Thanks for the hard work.

**Comment by mscdex** [comment]
SFTP does not provide a way for sending multiple filenames in a single stat request. You will need to find some other way, such as executing some command via `exec()`.
