### ISSUE TITLE
realPath platform inconsistency

### ISSUE THREAD

**Issue by theophilusx** [mscdex/ssh2-streams#165]
Not sure if this is a bug or just something which might need to be documented. 

When using realpath() to resolve a path on a Linux based server, if the remote path does not exist, the return value is an empty string ''. However, doing the same with a windows based server, a normalised path is returned regardless of whether the remote path actually exists or not. e.g.

On Linux

realpath('./not-exist/no-such-file.txt') => ''

On Windows

realpath('./not-exist/no-such-file.txt') => /C:/Users/tim/not-exist/no-such-file.txt'

On both systems the sftp server is openSSH

**Comment by mscdex** [comment]
That's completely server implementation-dependent. `ssh2-streams` does not modify any filenames/paths or do anything special for realpath requests/responses. So what you're seeing is exactly what the server responded with.

There have also been changes in OpenSSH over time that could impact things. For example: [their realpath implementation changed in OpenSSH 8.1](https://github.com/openssh/openssh-portable/commit/569b650f93b561c09c655f83f128e1dfffe74101) (they switched from relying on the OS's implementation of `realpath()` to their own custom implementation). So changes like this and others could also explain the difference in output, especially across platforms.

**Comment by theophilusx** [comment]
Thanks. That is useful information. I figured it was probably something like that. I think just having this issue on the record is probably enough to document possible different results depending on server. I'll close it now.
