### ISSUE TITLE
Add atomic transfer ability to fastPut?

### ISSUE THREAD

**Issue by virtuald** [mscdex/ssh2-streams#167]
Add an option if a server supports ext_openssh_rename, upload as a temporary filename, then once the transfer has completed rename to the actual filename.

If that sounds like something you'd accept adding here, I'm happy to implement it (though I don't know javascript very well... I want this for github actions).

**Comment by mscdex** [comment]
I think I'd prefer to leave that to userland to implement something like that. From my experience, convenience features like these typically end up being highly opinionated and I try to keep the module's focus on getting the core/less opinionated things right.

**Comment by virtuald** [comment]
Ok. thanks.

**Comment by virtuald** [comment]
@mscdex I looked a bit harder at this and my preference is to modify the behavior of `fastPut` that way I only need to implement the rename in one place (as putDirectory, etc all use it underneath the hood). Unfortunately, I didn't find a good mechanism to intercept the behavior, so I did it this way via a monkey patch: https://github.com/garygrossgarten/github-action-scp/blob/09a05dd06e8768d1327f701ef081f6f063834c3b/src/index.ts#L25

Generally speaking it seems that monkey patching is discouraged in Javascript, but there doesn't seem to be a hooking mechanism to insert the rename in there. Did I miss something? Would you be willing to insert a hook for this sort of thing, or do you think the monkey patching is fine.

Thanks! We've found this library (indirectly) to be really useful for automating our builds, I'm glad it exists. :)

**Comment by mscdex** [comment]
There is no hooking mechanism. A better alternative would be to just make it a new function (not on the prototype of course) instead of overwriting the existing `fastPut()` and have your application use that instead :man_shrugging:

**Comment by virtuald** [comment]
Well, but then I'd have to copy and change the massive bit of code that involved putting a directory, in addition to the file putting code....

Oh, I see! :facepalm: I had thought `putDirectory` was in this library, but it's in [node-ssh](https://github.com/steelbrain/node-ssh/blob/master/src/index.ts). I'll make a different issue there.
