### ISSUE TITLE
Unnecessary components are included in final module bundle

### ISSUE THREAD

**Issue by cmdcarini** [mscdex/ssh2-streams#169]
The `test`, `examples` dirs, among some other configuration files are included in the published module. This increases the size of the overall package, and includes a lot of test fixtures in the final bundle that aren't needed for its functionality. Consider specifying the exact files to include in the bundle using the [files attr in package.json](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#files)

**Comment by mscdex** [comment]
This module is in the process of being deprecated, so I don't see the point.
