### ISSUE TITLE
support kex algo sntrup761x25519-sha512@openssh.com

### ISSUE THREAD

**Issue by kylrth** [mscdex/ssh2-streams#187]
implement key exchange algorithm `sntrup761x25519-sha512@openssh.com`, which is the algorithm described in [this IETF memo](https://www.ietf.org/archive/id/draft-josefsson-ntruprime-hybrid-00.html)

**Comment by mscdex** [comment]
There's two issues here:

1. `ssh2` would be the more appropriate place for this as it is currently receiving updates whereas `ssh2-streams` is not, however...
2. OpenSSL does not have built-in support for sntrup761, which makes it reasonably impossible to support it in `ssh2` (unless you can convince node.js core to add the appropriate OpenSSL patches and expose access to sntrup761). It's possible a C++ addon could be written, but I'm very reluctant to do that for two reasons: I don't see the post-quantum algorithms as being that commonly used yet and people already complain about *optional* C++ addons (but perhaps the people really interested in the post-quantum algorithms do not intersect with that other group).
