### ISSUE TITLE
Impossible to do rm and mv commands over SFTP via client?

### ISSUE THREAD

**Issue by mikeatlas** [mscdex/ssh2-streams#19]
These are two commands I'd like to issue from the client, but don't seem possible (yet)?

Is there are reason or is it just not implemented yet?

**Comment by mikeatlas** [comment]
I even thought at first I could `mv` files into a `to_be_deleted` folder and then use the existing `rmdir` command; but without `mv` I can't do that either :/

**Comment by mscdex** [comment]
If you're doing a move, then you would use `rename()` just like you would with node's built-in `fs` module. After you move, there isn't anything to remove since it's an actual move and not a copy.

**Comment by mikeatlas** [comment]
(and then subsequently, I could call `rmdir`, right?) Would `rename` also create the directory if it didn't exist? Sorry, I'm not super familiar with the `fs` library, and appreciate the full explanation.

**Comment by mikeatlas** [comment]
Nevermind, I think I understand now. `unlink` to me in the `fs` library is a bit too close to `symlinks` and I glossed over the fact that `unlink` is indeed deleting the file.

**Comment by mscdex** [comment]
Yes, `rename()` is much like calling `mv` on a file or directory. So there is no need to call `rmdir` afterwards or having to creating a file or directory beforehand.
