### ISSUE TITLE
keyParser headers

### ISSUE THREAD

**Issue by almccann** [mscdex/ssh2-streams#38]
The OSX keychain exports RSA keys with a header `-----BEGIN RSA PUBLIC KEY-----`, regardless of the export format (SSH, SSH2, OpenSSL).  The private key begins `-----BEGIN RSA PRIVATE KEY-----`.

The keyParser doesn't anticipate this PEM armour.

Do you have any suggestions to integrate with this type of OSX export?

**Comment by mscdex** [comment]
You need the private key, not the public key. I'm not familiar with the OS X keychain in particular, but assuming you're actually using the key for connecting with an `ssh2` client, I'm guessing the OS X keychain has an ssh-agent interface somewhere? If so, you can just use that for user authentication instead (which is the most secure way of authenticating with a key anyway).

**Comment by almccann** [comment]
Hi @mscdex, thanks for that.

I ended up figuring out how to export from the OSX keychain in SSH2 format without the PEM armour, which produces the public key in the format that SSH2 stream utility expects.

So I have it working all together, thank you.
