### ISSUE TITLE
mkdirp method

### ISSUE THREAD

**Issue by elycruz** [mscdex/ssh2-streams#4]
Hi I was wondering whether there are any plans for a `mkdirp` method of if there is already away to get the functionality via the `mkdir` method (I'm using your `ssh2` module)?

**Comment by mscdex** [comment]
For `ssh2` you could just execute `mkdir`: `conn.exec('mkdir -p /foo/bar/baz', function(err, stream) { if (err) throw err; stream.resume(); stream.stderr.resume(); });` This is the simplest way because sftp is a pretty simple and low-level mechanism and as such does not support recursive `mkdir`.

**Comment by elycruz** [comment]
Awesome :+1: Thank you mscdex!
