### ISSUE TITLE
addding new cipher alghortims

### ISSUE THREAD

**Issue by hamedir** [mscdex/ssh2-streams#44]
Im trying to connect to a ssh server with the 'ssh2' module but the server ciphers' not match any of chipers on the ssh2-stream ciphers. here is ssh-session logs:
```

+LiveParser:DEBUG: Outgoing: Writing DISCONNECT (KEY_EXCHANGE_FAILED)

+LiveParser:DEBUG: No matching Client->Server cipher

+LiveParser:DEBUG: (remote) Client->Server ciphers: aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,arcfour,aes192-cbc,aes256-cbc

+LiveParser:DEBUG: (local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com

```
what should i do to able to add new cipher algorithms to the 'ssh2-stream'?
how could add those cipher to my app??

**Comment by mscdex** [comment]
Copying this from my answer to your SO question [here](http://stackoverflow.com/questions/38679325/):

The [documentation for `connect()`](https://github.com/mscdex/ssh2/#client-methods) shows all of the possible connection options. One of them (new in `ssh2` v0.5) is the `algorithms` option. You can explicitly set the list of ciphers to use during algorithm negotiation like so:

```js
conn.connect({
  // ...
  algorithms: {
    cipher: [
      'aes128-ctr',
      'aes192-ctr',
      'aes256-ctr',
      'aes128-gcm',
      'aes128-gcm@openssh.com',
      'aes256-gcm',
      'aes256-gcm@openssh.com',
      'aes256-cbc'
    ]
  }
});
```
