### ISSUE TITLE
Missing support for hmac-sha2-512-etm@openssh.com

### ISSUE THREAD

**Issue by Darkspirit** [mscdex/ssh2-streams#45]
Used in this configuration: https://github.com/mgrenier/remote-ftp/issues/445

**Comment by codexnovus** [comment]
Is this issue being considered for implementation?

**Comment by mscdex** [comment]
This should be resolved now with the `ssh2` rewrite. For more details see [here](https://github.com/mscdex/ssh2/issues/935).
