### ISSUE TITLE
How to set Type in Attrs()?

### ISSUE THREAD

**Issue by jclark-dot-org** [mscdex/ssh2-streams#50]
If I'm reading [section 7 of the SFTP Spec][1] correctly (and I may not be... very new to SFTP internals), shouldn't the Attrs structure always include a `type` byte?  Don't see it in the docs and don't see it in the code.  

Specifically, I'm implementing a Server, and I'm trying to implement REATPATH & STAT so that a client can execute 'cd /server/path' successfully.  When I try that from my client (Max OS X - /usr/bin/sftp), I see the REALPATH and STAT events on the server, but the client reports, "Can't change directory: "/server/path" is not a directory".  I'm guessing that's because the Attrs structure returned by STAT doesn't include the `SSH_FILEXFER_TYPE_DIRECTORY` value in the type byte.

[1]: https://tools.ietf.org/html/draft-ietf-secsh-filexfer-13#section-7

**Comment by mscdex** [comment]
You're referencing a newer version of SFTP (version 6), which is not supported by this module. This module supports only [version 3](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02) (the same as the OpenSSH SFTP implementation).

**Comment by jclark-dot-org** [comment]
Aha, thanks for the correct spec link and the complete explanation; everything is working correctly now.  I had wondered about the mode attribute, and I'd scanned the implementation of attrsToBytes(), but I didn't scroll far enough to see the Stats class and the helper functions there.  Perhaps a link in the attrs.mode section of the docs to the [Node docs for fs.constants][1] would prove helpful?  Thanks for this lib - so incredibly useful. 

[1]:https://nodejs.org/api/fs.html#fs_fs_constants_1
