### ISSUE TITLE
Handshake failed: no matching host key format

### ISSUE THREAD

**Issue by dev-head** [mscdex/ssh2-streams#51]
Hi There, 

I am hoping you can help me trace down this error that's coming from this lib. we have a service using this library to connect to sftp and when we moved the docker to another host one of the sftp accounts started failing and generating these errors. I can sftp directly from that node to the valid account, however we fail when using this library. 

I am a bit unsure what would be causing this, so any direction you can point me in is much appreciated. 

```
Error: Handshake failed: no matching host key format
    at check_KEXINIT (/var/www/node_modules/ssh2-streams/lib/ssh.js:2268:15)
    at check (/var/www/node_modules/ssh2-streams/lib/ssh.js:2179:9)
    at onKEXINIT (/var/www/node_modules/ssh2-streams/lib/ssh.js:2176:5)
    at SSH2Stream.<anonymous> (/var/www/node_modules/ssh2-streams/lib/ssh.js:204:39)
    at emitOne (events.js:77:13)
    at SSH2Stream.emit (events.js:169:7)
    at parse_KEXINIT (/var/www/node_modules/ssh2-streams/lib/ssh.js:4028:8)
    at parsePacket (/var/www/node_modules/ssh2-streams/lib/ssh.js:3927:12)
    at SSH2Stream._transform (/var/www/node_modules/ssh2-streams/lib/ssh.js:652:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/var/www/node_modules/ssh2-streams/lib/ssh.js:236:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
```

**Comment by mscdex** [comment]
If I had to guess, the remote host probably only has dss/dsa host keys, or other unsupported (by default) host key formats. You can verify this by setting `debug: console.log` in your connection config object. In `ssh2` v0.5.0, the default ciphers, host key formats, etc. changed to align with recent versions of OpenSSH. You can override these by providing absolute lists (`ssh2` does not have a way to just append or just remove individual list items like OpenSSH does with the `+` and `-` prefixes to names) via the `algorithms` property in the connection config object. See the documentation for the format of this object.

At any rate, I will try to add the local and remote lists to the error (in one way or another) so it's more evident what both sides support.

**Comment by mscdex** [comment]
Also, what version of node are you using?

**Comment by dev-head** [comment]
the kicker is that it is working fine on another node, pretty much everything i can control is the same between the nodes. 

current node version on both servers: v4.2.3

----

update: i think it's a build issue. lets close this out and i'll debug with dev later. thanks!

**Comment by dev-head** [comment]
Hi @mscdex, 

It looks like the issue we had was related to an update which removed support for "ssh-dss". I tested with a modified ```lib/constants.js``` and changed the below variable setting. This seemingly allowed us to at least get past the error we were running into. 

We ended up pinning down our dependencies back to an earlier version which had some different logic. I'm not sure if this change I tested is a fix for an issue or if it was just cheating, so i'm not going to submit a PR for it. I'll just leave this as reference in case it's really an issue or perhaps just needs to be detailed a bit more how to address it. 

From:
```
var DEFAULT_SERVER_HOST_KEY = [
    'ssh-rsa'
];
```

To:
```
var DEFAULT_SERVER_HOST_KEY = [
    'ssh-rsa', 
    'ssh-dss'
];
```

**Comment by mscdex** [comment]
As I previously mentioned, you can already change the list of algorithms used during the handshake by setting the `algorithms` property of the connection config appropriately, so there is no need to modify the module's source code. For example:

```js
ssh.connect({
  // ...
  algorithms: {
    serverHostKey: [ 'ssh-rsa', 'ssh-dss' ],
  }
});
```

**Comment by Pushpinder2751** [comment]
Could you please explain how to do this? and where?

**Comment by jasoncheow** [comment]
@Pushpinder2751 The following example works for me:

```
var ssh2 = require('ssh2')
var Client = require('ssh2').Client
var conn = new Client()
conn.on('ready', () => {
  console.log('Client :: ready')
}).connect({
  host: 'xxx',
  port: '22',
  username: 'xxx',
  password: 'xxx',
  algorithms: {
    serverHostKey: ['ssh-rsa', 'ssh-dss']
  }
})
```
