### ISSUE TITLE
Invalid returned stats?

### ISSUE THREAD

**Issue by pyrsmk** [mscdex/ssh2-streams#52]
Hi,

When I do a `sftp.stat` on a path, the stats var has no `isDirectory()` method (or any method related in the [docs](https://github.com/mscdex/ssh2-streams/blob/master/SFTPStream.md#stats). Is there something I'm missing?

**Comment by mscdex** [comment]
It works for me, how are you determining that it has no such method?

**Comment by mscdex** [comment]
Also, what version of `ssh2-streams` are you using?

**Comment by pyrsmk** [comment]
I have the `0.1.12` version. And there is no such method because NPM fails on it (`undefined si not a function` or something like that). I verified the `stats` object and it has only `attrs` properties. Here's what I'm doing : 

```js
/*
    - sftpClient is just a wrapper to handle ssh2 as expected by gulp
    - sftpClient.exec() is a tiny wrapper that executes a SFTP command and passes vars to the callback (without `err`, which is already handled by exec())
*/
sftpClient.exec('stat', [filepath], function(stats) {
    if(stats.isDirectory()) {
        sftpClient.rmdir(filepath);
    }
    else {
        sftpClient.unlink(filepath);
    }
});
```

**Comment by mscdex** [comment]
Oh, you're using something that wraps `ssh2`/`ssh2-streams`, that could be why...
Could it be that it's actually executing that as a command and parsing the output and not *actually* using the sftp subsystem's `stat()`? Where is the `sftpClient` object defined, or what third party module are you using that provides this object/interface (if applicable)?

**Comment by pyrsmk** [comment]
It executes the command with `sftp[command].apply(sftp, params)` which gives us `sftp.stat(path, cb)`. Maybe I put the wrong var for the `this` keyword (I found that putting `sftp` here solves the issues I had).

**Comment by pyrsmk** [comment]
I've created the `sftpClient` myself. It handles log messages, connection, sftp commands, dest site copy, recursive mkdir and remote site cleaning.

**Comment by mscdex** [comment]
Assuming

```js
sftpClient.exec('stat', [filepath], function(stats) {
```

is actually doing

```js
sftp.stat(filepath, function(stats) {
```

then perhaps the problem is that you only have one parameter in your callback? Node-style callbacks are used, so it should be `(err, stats)` instead of `(stats)`.

**Comment by pyrsmk** [comment]
In fact,

```js
sftpClient.exec('stat', [filepath], function(stats) {
```

is valid, since `exec()` only returns parameters without `err`, because it's handled/filtered directly by `exec()`.

I remember that I already did a stat in another part of the program, and the object returned was the same : only `attrs`, no `stats`. That stat was run without the `exec()`, so it was really clean. Can this be an issue with the sftp server itself?

**Comment by mscdex** [comment]
Doubtful. If you can come up with a complete, minimal, reproducible example, I would be happy to look into the problem.

**Comment by pyrsmk** [comment]
Ok! I'll refactor some stuff, create a simple example and come back to you ;)

**Comment by pyrsmk** [comment]
So, it seems the issue comes from my code, I don't know exactly why. Anyway, with the simple example, I have all the methods in `stats`.

**Comment by pyrsmk** [comment]
Ok. So. Bad arguments were passed to my callback ^^;
Sorry for this waste of time.
