### ISSUE TITLE
Standalone SFTP over stream?

### ISSUE THREAD

**Issue by SourceBoy** [mscdex/ssh2-streams#59]
If I already have a full-duplex stream between 2 parties (without SSH), is the SFTPStream module capable of listening/operating over the stream? i.e. Just the SFTP protocol implementation over stream but without SSH dependency.

**Comment by mscdex** [comment]
Yes.

**Comment by SourceBoy** [comment]
That's a brilliant design & implementation being able to use just the SFTP protocol by itself. Is the recommended usage simply `class MyStream extends SFTPStream` with `config.server = true` on one side and `config.server = false` on the other side to get things going?

Are there any specific functionalities that one needs to be aware of when there isn't SSH on either side?

**Comment by mscdex** [comment]
I've not done a whole lot of ES6 class stuff, but I would guess that would be what you would do to subclass it for some reason.

As far as using it, yes, the bare minimum would be setting the `server` property in the config object appropriately.

Specific functionalities? What did you have in mind? Once the stream is instantiated, it's just a matter of using it like any other node stream. Pipe it to/from a socket or wherever you want.
