### ISSUE TITLE
createWriteStream encoding

### ISSUE THREAD

**Issue by ItamarAbeliovich** [mscdex/ssh2-streams#66]
I tried writing an image to the remote server, both as a base64 string and as a binary string. I set the options to {encoding: 'base64'} and {encoding: 'binary'}, both did nothing and the file got written as plain text with the base64 string being in it. How do I properly write non-text files?

**Comment by mscdex** [comment]
Can you supply example code to reproduce the problem?

**Comment by ItamarAbeliovich** [comment]
nevermind, apparently supplying a buffer to the function will write it properly.
