### ISSUE TITLE
Responding to a READDIR request - folders always being listed as files

### ISSUE THREAD

**Issue by tkambler** [mscdex/ssh2-streams#81]
I'm responding to a READDIR request with the following data:

```
[
    {
        "filename": "stuff.txt",
        "longname": "-rw------- 1 foo foo 20 Sep 8 14:39 stuff.txt",
        "attrs": {
            "mode": "0600",
            "size": 20,
            "atime": 1504900534,
            "mtime": 1504899577
        }
    },
    {
        "filename": "things",
        "longname": "drw------- 2 foo foo 68 Sep 8 14:48 things",
        "attrs": {
            "mode": "0600",
            "size": 68,
            "atime": 1504901150,
            "mtime": 1504900080
        }
    }
]
```

`things` is a directory, but my SFTP client (Transmit) thinks it is a file. Am I doing something wrong?

**Comment by mscdex** [comment]
Your `mode` is not correct. Besides the permissions, the `mode` can contain some higher bits that indicate type and other flags. Node's `fs` module has many of these flags, so for a directory you could do something like:

```js
mode: 0o600 | fs.constants.S_IFDIR
```

**Comment by tkambler** [comment]
@mscdex Thank you for such a quick response!
