### ISSUE TITLE
SSH2 / SSH2-Streams over browser's websockets?

### ISSUE THREAD

**Issue by ivucica** [mscdex/ssh2-streams#88]
Hi,

[Secure Shell for Chrome](https://chromium.googlesource.com/apps/libapps/+show/master/nassh) can use a [relay](https://chromium.googlesource.com/apps/libapps/+/master/nassh/doc/FAQ.md) as a connection proxy.

As far as I can interpret it, there are some REST calls to authenticate (if required), then establish a session toward an SSH server which provides a session ID, which can then be used to establish a websocket tunneling raw SSH traffic.

There is at least one open source implementation of the relay: [nassh-relay](https://github.com/zyclonite/nassh-relay).

Currently, ssh2-streams and ssh2 seem to be targeting node.js only. Are ssh-streams and ssh2 usable in a browser environment, talking SSH2 protocol over an established, provided websocket? Would it be of interest to support this use case?

**Comment by mofux** [comment]
This library (only considering the streams part) depends on many modules provided by node.js, like crypto, zlib and streams. Even if you could polyfill these, it would mean a massive rewrite of ssh2-streams. I can see your use-case for parsing ssh traffic in the browser, but I don't think this module will be able to provide it.

**Comment by mscdex** [comment]
You'd have to shim all of the necessary built-in node modules, like `crypto`, etc., which may not be easy. I know there are *some* such efforts on npm, such as [`crypto-browserify`](https://www.npmjs.com/package/crypto-browserify).

FWIW you can pass a node `Duplex` stream (as `sock`) in the config object passed to `ssh2.Client`'s `connect()` and `ssh2` will use that instead of creating a TCP connection. This was originally added to facilitate connection hopping, but it would be useful in this particular use case as well, although you may have to perform some minimal shimming to at least allow `require('net')`.

**Comment by mscdex** [comment]
Also, doing ssh2 in the browser doesn't make a lot of sense IMHO. Just let the server/relay handle that. One benefit to this is that you don't have to transfer so much data back and forth between the browser and server/relay.

**Comment by ivucica** [comment]
> Also, doing ssh2 in the browser doesn't make a lot of sense IMHO. Just let the server/relay handle that. 

Except the relay sees the traffic between the SSHD and the client.

The use case is not just processing SSH traffic in the browser -- it's also making the relay unaware of the traffic passing through it, unaware of the credentials going through it, etc.

**Comment by mscdex** [comment]
Well, there'd still be a fair amount of work as far as I can tell and I would still be concerned about the crypto implementations. The Web Crypto API might be able to help here, but even that has its own issues, such as there being no required algorithms for User Agents (only a "recommended" list) and you'd still need a shim on top of that. You'd also need all of the other needed node modules that I previously alluded to.

So it's certainly *possible* I suppose, but it will take a lot of work I think depending on what shims are available.
