### ISSUE TITLE
mkdir followed by createWriteStream causes "Error: You cannot pipe after data has been emitted from the response." sometimes

### ISSUE THREAD

**Issue by soichih** [mscdex/ssh2-streams#89]
I am obtaining sftp connection from ssh2.connect(), then running sftp.mkdir() followed by createWriteStream to send file from local machine.

I then commence transferring data by doing following.

```
readstream.pipe(writestream);
```

When I do, I *sometimes* receives following error message.

> Error: You cannot pipe after data has been emitted from the response.

I have an async for loop to run multiple paris of sftp.mkdir() and uploading files to the sftp server. I usually run into the issue within 2nd or 3rd file.

If I don't run mkdir(), I can keep uploading files without the error message. I believe there is a bug within sftp.mkdir() that corrupts the next streaming.. or something.. but I am not sure. I also saw a note about "continue" event sometimes generated that I need to wait for, but my sftp() calls alway return true. (And the documentation doesn't describe what "continue" events are, and why I need it, etc..)

Thank you!

**Comment by mscdex** [comment]
A brief google shows 'You cannot pipe after data has been emitted from the response' is an error coming from the module `request`, not from this module or node core.

**Comment by soichih** [comment]
I found what the issue was. sftp.createWriteStream() by-default closes sftp session after the pipe closes. I've updated it to this

```
let writestream = sftp.createWriteStream(path, {autoClose: false});
```

**Comment by mscdex** [comment]
Yep, that mirrors the node `fs` API. I'm glad you found a solution though.
